create_clock -period 10.000 -name PinClk -waveform {0.000 5.000} [get_ports PinClk]

set_property PACKAGE_PIN C18 [get_ports PinARst_N]
set_property IOSTANDARD LVCMOS33 [get_ports PinARst_N]

set_property PACKAGE_PIN R2 [get_ports PinClk]
set_property IOSTANDARD LVCMOS33 [get_ports PinClk]

set_property PACKAGE_PIN V12 [get_ports PinRx]
set_property PACKAGE_PIN R12 [get_ports PinTx]
set_property IOSTANDARD LVCMOS33 [get_ports PinTx]
set_property IOSTANDARD LVCMOS33 [get_ports PinRx]


set_property PACKAGE_PIN E18 [get_ports {PinLed[0]}]
set_property PACKAGE_PIN F13 [get_ports {PinLed[1]}]
set_property PACKAGE_PIN E13 [get_ports {PinLed[2]}]
set_property PACKAGE_PIN H15 [get_ports {PinLed[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PinLed[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PinLed[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PinLed[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PinLed[0]}]
#
#
#set_property IOSTANDARD LVCMOS33 [get_ports {PinSw[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {PinSw[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {PinSw[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {PinSw[0]}]
#set_property PACKAGE_PIN H14 [get_ports {PinSw[0]}]
#set_property PACKAGE_PIN H18 [get_ports {PinSw[1]}]
#set_property PACKAGE_PIN G18 [get_ports {PinSw[2]}]
#set_property PACKAGE_PIN M5 [get_ports {PinSw[3]}]
#
#set_property IOSTANDARD LVCMOS33 [get_ports PinRGBLed*]
#set_property PACKAGE_PIN F15 [get_ports {PinRGBLed[0]}]
#set_property PACKAGE_PIN G17 [get_ports {PinRGBLed[1]}]
#set_property PACKAGE_PIN J15 [get_ports {PinRGBLed[2]}]
#set_property PACKAGE_PIN E14 [get_ports {PinRGBLed[3]}]
#set_property PACKAGE_PIN E15 [get_ports {PinRGBLed[4]}]
#set_property PACKAGE_PIN F18 [get_ports {PinRGBLed[5]}]

set_property PACKAGE_PIN U11 [get_ports PinAnemoOut]
set_property IOSTANDARD LVCMOS33 [get_ports PinAnemoOut]
set_property PACKAGE_PIN T11 [get_ports PinGiroPwm]
set_property IOSTANDARD LVCMOS33 [get_ports PinGiroPwm]
set_property PACKAGE_PIN R11 [get_ports PinCapPwm]
set_property IOSTANDARD LVCMOS33 [get_ports PinCapPwm]
set_property PACKAGE_PIN L13 [get_ports PinVerinPwm]
set_property IOSTANDARD LVCMOS33 [get_ports PinVerinPwm]
set_property PACKAGE_PIN T14 [get_ports PinVerinAngleSck]
set_property IOSTANDARD LVCMOS33 [get_ports PinVerinAngleSck]
set_property PACKAGE_PIN T12 [get_ports PinVerinAngleMiso]
set_property IOSTANDARD LVCMOS33 [get_ports PinVerinAngleMiso]
set_property PACKAGE_PIN R14 [get_ports PinVerinAngleCs_N]
set_property IOSTANDARD LVCMOS33 [get_ports PinVerinAngleCs_N]
set_property PACKAGE_PIN N13 [get_ports PinVerinSens]
set_property IOSTANDARD LVCMOS33 [get_ports PinVerinSens]

set_property PACKAGE_PIN V15 [get_ports PinLedBabord]
set_property IOSTANDARD LVCMOS33 [get_ports PinLedBabord]
set_property PACKAGE_PIN U12 [get_ports PinLedStandby]
set_property IOSTANDARD LVCMOS33 [get_ports PinLedStandby]
set_property PACKAGE_PIN V13 [get_ports PinLedTribord]
set_property IOSTANDARD LVCMOS33 [get_ports PinLedTribord]
set_property PACKAGE_PIN V17 [get_ports PinBtnBabord]
set_property IOSTANDARD LVCMOS33 [get_ports PinBtnBabord]
set_property PACKAGE_PIN R17 [get_ports PinBtnStandby]
set_property IOSTANDARD LVCMOS33 [get_ports PinBtnStandby]
set_property PACKAGE_PIN R16 [get_ports PinBtnTribord]
set_property IOSTANDARD LVCMOS33 [get_ports PinBtnTribord]

# Test points
set_property PACKAGE_PIN P13 [get_ports {PinTp[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PinTp[0]}]
set_property PACKAGE_PIN R13 [get_ports {PinTp[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PinTp[1]}]
set_property PACKAGE_PIN V14 [get_ports {PinTp[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PinTp[2]}]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list PinClk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {uSimu/uVerinAngle/uSpiSlave/CptBit[0]} {uSimu/uVerinAngle/uSpiSlave/CptBit[1]} {uSimu/uVerinAngle/uSpiSlave/CptBit[2]} {uSimu/uVerinAngle/uSpiSlave/CptBit[3]} {uSimu/uVerinAngle/uSpiSlave/CptBit[4]} {uSimu/uVerinAngle/uSpiSlave/CptBit[5]} {uSimu/uVerinAngle/uSpiSlave/CptBit[6]} {uSimu/uVerinAngle/uSpiSlave/CptBit[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 12 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {uSimu/uVerinAngle/sAnalog[0]} {uSimu/uVerinAngle/sAnalog[1]} {uSimu/uVerinAngle/sAnalog[2]} {uSimu/uVerinAngle/sAnalog[3]} {uSimu/uVerinAngle/sAnalog[4]} {uSimu/uVerinAngle/sAnalog[5]} {uSimu/uVerinAngle/sAnalog[6]} {uSimu/uVerinAngle/sAnalog[7]} {uSimu/uVerinAngle/sAnalog[8]} {uSimu/uVerinAngle/sAnalog[9]} {uSimu/uVerinAngle/sAnalog[10]} {uSimu/uVerinAngle/sAnalog[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {uSimu/uVerinAngle/uSpiSlave/vTxDat[0]} {uSimu/uVerinAngle/uSpiSlave/vTxDat[1]} {uSimu/uVerinAngle/uSpiSlave/vTxDat[2]} {uSimu/uVerinAngle/uSpiSlave/vTxDat[3]} {uSimu/uVerinAngle/uSpiSlave/vTxDat[4]} {uSimu/uVerinAngle/uSpiSlave/vTxDat[5]} {uSimu/uVerinAngle/uSpiSlave/vTxDat[6]} {uSimu/uVerinAngle/uSpiSlave/vTxDat[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list uSimu/uVerinAngle/uSpiSlave/CurrentST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list uSimu/uVerinAngle/uSpiSlave/vMiso]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list uSimu/uVerinAngle/uSpiSlave/vMosi]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list uSimu/uVerinAngle/uSpiSlave/vRxVld]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list uSimu/uVerinAngle/uSpiSlave/vSck]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list uSimu/uVerinAngle/uSpiSlave/vSs]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets PinClk_IBUF_BUFG]
