create_clock -period 10.000 -name PinClk -waveform {0.000 5.000} [get_ports PinClk]

set_property PACKAGE_PIN V12 [get_ports PinRx]
set_property PACKAGE_PIN R12 [get_ports PinTx]
set_property IOSTANDARD LVCMOS33 [get_ports PinTx]
set_property IOSTANDARD LVCMOS33 [get_ports PinRx]
set_property IOSTANDARD LVCMOS33 [get_ports PinARst_N]
set_property PACKAGE_PIN C18 [get_ports PinARst_N]
set_property PACKAGE_PIN E18 [get_ports {PinLed[0]}]
set_property PACKAGE_PIN F13 [get_ports {PinLed[1]}]
set_property PACKAGE_PIN E13 [get_ports {PinLed[2]}]
set_property PACKAGE_PIN H15 [get_ports {PinLed[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PinLed[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PinLed[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PinLed[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PinLed[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports PinClk]
set_property PACKAGE_PIN R2 [get_ports PinClk]


set_property IOSTANDARD LVCMOS33 [get_ports {PinSw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PinSw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PinSw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PinSw[0]}]
set_property PACKAGE_PIN H14 [get_ports {PinSw[0]}]
set_property PACKAGE_PIN H18 [get_ports {PinSw[1]}]
set_property PACKAGE_PIN G18 [get_ports {PinSw[2]}]
set_property PACKAGE_PIN M5 [get_ports {PinSw[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {PinRGBLed*}]
set_property PACKAGE_PIN F15 [get_ports {PinRGBLed[0]}]
set_property PACKAGE_PIN G17 [get_ports {PinRGBLed[1]}]
set_property PACKAGE_PIN J15 [get_ports {PinRGBLed[2]}]
set_property PACKAGE_PIN E14 [get_ports {PinRGBLed[3]}]
set_property PACKAGE_PIN E15 [get_ports {PinRGBLed[4]}]
set_property PACKAGE_PIN F18 [get_ports {PinRGBLed[5]}]

