-- Simu.vhd

-- Generated using ACDS version 20.1 720

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Simu is
end entity Simu;

architecture rtl of Simu is
	component Simu_Simulator_0 is
	end component Simu_Simulator_0;

begin

	simulator_0 : component Simu_Simulator_0
		port map (
		);

end architecture rtl; -- of Simu
